n1= int(input('Primeiro número: '))
n2= int(input('Segundo número: '))
if n1>n2: print(' O primeiro número é maior que o segundo')
elif n1 == n2: print('O dois números tem o mesmo valor.')
else: print('O segundo número é maior que o primeiro.')